name: BitBucket Server Migration Tool Windows
on:
  workflow_dispatch:
  
jobs: 
  Get-Repositories-to-Migrate:
      runs-on: ubuntu-latest
      outputs:
        REPOSITORIES: ${{ steps.set-matrix.outputs.REPO }}
        OWNER: ${{ steps.set-owner.outputs.OW}}
        
      steps:
        - name: Checkout to repository
          uses: actions/checkout@v3
       
        - name: Set matrix data
          id: set-matrix
          run: |
            echo "REPO=$(jq -c -r '.repositories | map(.repo_name)' < ./repositories.json)" >> $GITHUB_OUTPUT 
            echo "$REPO"
            
        - name: Set owner
          id: set-owner
          run: |
            echo "OW=$(jq -r '.owner' repositories.json)" >> $GITHUB_OUTPUT 
            echo "$OW"
        
  Migration:
    runs-on: [ 'self-hosted' , 'Linux' , 'X64' ]
    needs: Get-Repositories-to-Migrate
    strategy:
      max-parallel: 1
      # SET MATRIX WITH PROJECTS TO MIGRATE
      matrix:
        repository: ${{fromJson(needs.Get-Repositories-to-Migrate.outputs.REPOSITORIES)}}
      
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
              
      - name: Migration
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BBS_USERNAME: ${{ secrets.BBS_USERNAME }}
          BBS_PASSWORD: ${{ secrets.BBS_PASSWORD }}
          BBS_TOKEN: ${{ secrets.BBS_TOKEN }}
          OWNER: ${{ needs.Get-Repositories-to-Migrate.outputs.OWNER }}
        run:
          echo "${{ env.OWNER }}"
          
      - name: Check if repository exists
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GH_PAT }}" "https://api.github.com/repos/jgonzalez-clevermig-test/${{ matrix.repository }}")

            # Verificar el código de respuesta
            if [ "$response" -eq 200 ]; then
              echo "El repositorio jgonzalez-clevermig-test/${{ matrix.repository }} existe."
              exit 1  # Salir con un código de error
            else
              echo "Error: El repositorio jgonzalez-clevermig-test/${{ matrix.repository }} no existe."
              
            fi

      #- name: Pull request
      #  run: |
      #    curl -X GET \
      #    http://localhost:7990/rest/api/latest/projects/${{ env.OWNER }}/repos/repo-test/pull-requests \
      #    -H 'Accept: application/json' \
      #    -H 'Authorization: Bearer ${{ secrets.BBS_TOKEN }}' \
      #    -o bbs_pullrequest.json
          
      - name: Clone BitBucket Repository {{ item.bbs_repository_name }}
        run: |
          git clone http://${{ secrets.BBS_USERNAME }}:${{ secrets.BBS_PASSWORD }}@localhost:7990/scm/proj/${{ matrix.repository }}.git --mirror

      - name: Crate repository on Github
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/jgonzalez-clevermig-test/repos \
            -d '{"name":"${{ matrix.repository }}","private":true}'

      - name: Push repository to Github
        run: |
          cd ${{ matrix.repository }}.git
          git remote add github "https://${{ secrets.GH_PAT }}@github.com/jgonzalez-clevermig-test/${{ matrix.repository }}.git"
          git push github --mirror

      - name: Clean runner
        run: |
          pwd
          ls
          # rm **      

          
