name: BitBucket Server Migration Tool Windows
on:
  workflow_dispatch:
  
jobs: 
  Get-Repositories-to-Migrate:
      runs-on: ubuntu-latest
      outputs:
        REPOSITORIES: ${{ steps.set-matrix.outputs.REPO }}
        OWNER: ${{ steps.set-owner.outputs.OW}}
        
      steps:
        - name: Checkout to repository
          uses: actions/checkout@v3
       
        - name: Set matrix data
          id: set-matrix
          run: |
            echo "REPO=$(jq -c -r '.repositories | map(.repo_name) | join(",")' < ./repositories.json)' < ./repositories.json)" >> $GITHUB_OUTPUT 
            echo "$REPO"
        - name: Set owner
          id: set-owner
          run: |
            echo "OW=$(jq -r '.owner' repositories.json)" >> $GITHUB_OUTPUT 
            echo "$OW"
        
  Migration:
    runs-on: [ 'self-hosted' , 'Linux' , 'X64' ]
    needs: Get-Repositories-to-Migrate
    strategy:
      max-parallel: 1
      # SET MATRIX WITH PROJECTS TO MIGRATE
      matrix: ${{ fromJson(needs.Get-Repositories-to-Migrate.outputs.REPOSITORIES) }}
      
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
              
      - name: Migration
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BBS_USERNAME: ${{ secrets.BBS_USERNAME }}
          BBS_PASSWORD: ${{ secrets.BBS_PASSWORD }}
          BBS_TOKEN: ${{ secrets.BBS_TOKEN }}
          OWNER: ${{ needs.Get-Repositories-to-Migrate.outputs.OWNER }}
          
        run: |
          ls
          echo "${{ env.OWNER }}"


      - name: Pull request
        run: |
          curl -X GET \
          http://localhost:7990/rest/api/latest/projects/${{ env.OWNER }}/repos/repo-test/pull-requests \
          -H 'Accept: application/json' \
          -H 'Authorization: Bearer ${{ secrets.BBS_TOKEN }}' \
          -o bbs_pullrequest.json
          
      - name: Clone BitBucket Repository {{ item.bbs_repository_name }}
        run: git clone http://${{ secrets.BBS_USERNAME }}:${{ secrets.BBS_PASSWORD }}@localhost:7990/scm/proj/repo-test.git

          
